// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ShowEntityLimit
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ShowEntityLimit";
        public const string Version     = "0.1.0";
        public const string Title       = "Show Entity Limit";
        public const string Description = "Shows the current and maximum number of entities that exists in a Cities: Skylines 2 save ";
    }
}
